
import React from 'react';
import { Helmet } from 'react-helmet-async';
import { AlertTriangle } from 'lucide-react';

const LegalDisclaimer = () => {
  return (
    <>
      <Helmet>
        <title>Legal Disclaimer - FamilyBridge | Atlanta, GA</title>
        <meta name="description" content="Important legal information and disclaimers about FamilyBridge's AI-powered child support preparation service for Atlanta and Fulton County." />
      </Helmet>

      <main className="min-h-screen pt-24 pb-16 bg-[var(--cream)]">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h1 className="text-4xl sm:text-5xl font-black text-[var(--ink)] mb-6 font-display">
              Legal <span className="text-[var(--rose)]">Disclaimer</span>
            </h1>
            <p className="text-lg text-[var(--moss)] opacity-80">
              Important information about our service
            </p>
          </div>

          <div className="bg-[rgba(139,177,167,0.12)] border border-[rgba(139,177,167,0.3)] rounded-2xl p-6 mb-8 flex items-start gap-4">
            <AlertTriangle className="h-6 w-6 text-[var(--moss)] flex-shrink-0 mt-1" />
            <div>
              <h2 className="text-lg font-bold text-[var(--ink)] mb-2">Important Notice</h2>
              <p className="text-[var(--moss)] opacity-80">
                FamilyBridge provides AI-powered analysis and information services. We are not a law firm and do not provide legal advice or representation.
              </p>
            </div>
          </div>

          <div className="bg-white/80 backdrop-blur-lg border border-[var(--linen)] rounded-3xl p-8 sm:p-12 space-y-8">
            <section>
              <h2 className="text-2xl font-bold text-[var(--ink)] mb-4">Not Legal Advice</h2>
              <p className="text-[var(--moss)] opacity-80 mb-4">
                The information and analysis provided by FamilyBridge is for informational purposes only and does not constitute legal advice. The use of our service does not create an attorney-client relationship between you and FamilyBridge or any of its employees or contractors.
              </p>
              <p className="text-[var(--moss)] opacity-80">
                For legal advice specific to your situation, please consult with a licensed attorney in your jurisdiction.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-[var(--ink)] mb-4">AI Analysis Limitations</h2>
              <p className="text-[var(--moss)] opacity-80 mb-4">
                Our AI system analyzes child support documents based on patterns, guidelines, and structured data. While we strive for accuracy, the analysis is generated by artificial intelligence and may not account for all nuances of your specific case or local laws.
              </p>
              <p className="text-[var(--moss)] opacity-80">
                Results and success rates are based on historical data and do not guarantee specific outcomes for your case.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-[var(--ink)] mb-4">No Guarantee of Results</h2>
              <p className="text-[var(--moss)] opacity-80 mb-4">
                While our strategies have helped many families prepare for court, we cannot guarantee any specific outcome. Court outcomes depend on many factors including:
              </p>
              <ul className="list-disc list-inside space-y-2 text-[var(--moss)] ml-4 opacity-80">
                <li>Local laws and court procedures</li>
                <li>Specific circumstances of your case</li>
                <li>Quality of evidence and presentation</li>
                <li>Judge and prosecutor discretion</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-[var(--ink)] mb-4">User Responsibility</h2>
              <p className="text-[var(--moss)] opacity-80 mb-4">
                By using FamilyBridge, you acknowledge that:
              </p>
              <ul className="list-disc list-inside space-y-2 text-[var(--moss)] ml-4 opacity-80">
                <li>You are responsible for verifying all information provided</li>
                <li>You should consult local court rules and procedures</li>
                <li>You may want to seek professional legal counsel</li>
                <li>You understand the risks involved in a court process</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-[var(--ink)] mb-4">Service Limitations</h2>
              <p className="text-[var(--moss)] opacity-80">
                FamilyBridge's analysis is based on the information you provide. Inaccurate, incomplete, or outdated information may result in less effective strategies. Our service does not include:
              </p>
              <ul className="list-disc list-inside space-y-2 text-[var(--moss)] ml-4 mt-4 opacity-80">
                <li>Court representation or appearance on your behalf</li>
                <li>Direct communication with courts or law enforcement</li>
                <li>Filing of legal documents (unless specifically arranged)</li>
                <li>Ongoing legal counsel or case management</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-[var(--ink)] mb-4">Refund Policy</h2>
              <p className="text-[var(--moss)] opacity-80">
                Our refund policy applies only if we cannot generate a strategy draft based on the information provided. The policy does not apply to court outcomes or user error in implementing recommendations.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-[var(--ink)] mb-4">Privacy & Data Security</h2>
              <p className="text-[var(--moss)] opacity-80">
                We take your privacy seriously and use industry-standard encryption to protect your data. However, you should be aware that transmitting information over the internet carries inherent risks. See our Privacy Policy for complete details.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-[var(--ink)] mb-4">Limitation of Liability</h2>
              <p className="text-[var(--moss)] opacity-80">
                FamilyBridge and its affiliates shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use our service, even if we have been advised of the possibility of such damages.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-[var(--ink)] mb-4">Updates to This Disclaimer</h2>
              <p className="text-[var(--moss)] opacity-80">
                We reserve the right to update this disclaimer at any time. Continued use of our service after changes constitutes acceptance of the updated terms.
              </p>
            </section>

            <section className="pt-4 border-t border-[var(--linen)]">
              <p className="text-[var(--moss)] text-sm opacity-70">
                Last updated: December 23, 2025
              </p>
              <p className="text-[var(--moss)] text-sm mt-2 opacity-70">
                If you have questions about this disclaimer, please contact us at legal@familybridge.ai
              </p>
            </section>
          </div>
        </div>
      </main>
    </>
  );
};

export default LegalDisclaimer;
